# Generated by Django 5.0.1 on 2024-02-16 14:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="animedata",
            options={"managed": False},
        ),
    ]
