# Generated by Django 5.0.1 on 2024-02-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Core", "0002_alter_animedata_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnimeDaatabase",
            fields=[
                ("mal_id", models.BigIntegerField(blank=True,primary_key=True)),
                ("title", models.TextField(blank=True, null=True)),
                ("url", models.TextField(blank=True, null=True)),
                ("images", models.TextField(blank=True, null=True)),
                ("trailer", models.TextField(blank=True, null=True)),
                ("titles", models.TextField(blank=True, null=True)),
                ("type", models.TextField(blank=True, null=True)),
                ("episodes", models.BigIntegerField(blank=True, null=True)),
                ("aired", models.TextField(blank=True, null=True)),
                ("source", models.TextField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
                ("duration", models.TextField(blank=True, null=True)),
                ("rating", models.TextField(blank=True, null=True)),
                ("synopsis", models.TextField(blank=True, null=True)),
                ("rank", models.BigIntegerField(blank=True, null=True)),
                ("popularity", models.BigIntegerField(blank=True, null=True)),
                ("genre", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "Anime_daatabase",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="AnimeData",
        ),
    ]
